const toggle = document.querySelector('#toggle')
const nav = document.querySelector('#nav')

const luzerinUno = [
  {
    numeroCapitulo: '1',
    NombreCapitulo: 'Colibri de Madera',
    Texto: [
      'El mundo de la magia existe, aunque muchos trabajan para mantenerlo oculto. Y debemos reconocerle que lo logran con mucha efectividad. Cualquiera podría pensar que esta declaración es un disparate o que la magia solo pertenece al mundo de la fantasía. Anahí Zem también lo creía. A veces, la vida nos pone adelante, eso que debemos reconocer y no logramos percibir. Se encontraba en la Calle de las Sensaciones, específicamente en el bar Al+. Sentada en una mesa que daba a la ventana, miró afuera, pocos deambulaban. Con detenimiento observó la carta. Llamó al mozo y le pidió una regresión en el tiempo, para recorrer el comienzo de su aventura. Con la intención de clarificar sus aspiraciones. Tal vez rememorando lo vivido, apareciera alguna señal. Esperó.',
      'Bebió un trago para darse ánimos. En la noche tendría la ceremonia de bienvenida a la Fortaleza de Lúzerin. Intentaría obtener para esa ocasión,  al menos una leve idea de dónde poner su cuerpo, en qué equipo ocupar un rol, dar su tiempo de vida, su trabajo cotidiano. Tomó los lentes, se los puso. Su memoria le lanzaba imágenes. Sintió que su cuerpo se estiraba. Perdió el sentido espacial y la conciencia. Cuando la recobró, se vió a sí misma, semi recostada en un sillón mugroso, abandonado en el frente de su casa. Vivía en un pequeño pueblo llamado Cumén, del lado de la costa atlántica, en la provincia de Santa Cruz, Argentina. Dos años caminando por las calles de tierra, el frío áspero del sur, la arena y el mar. El olor al mar la tranquilizaba. Cuando palpaba la soledad, extrañaba Buenos Aires, el oeste, el agite. La noche, las exposiciones de arte, la música en vivo, los bares. Nació una tarde de tormenta. Anahí, no sabes cómo llovía cuando naciste. Vos sí que vas a limpiar a varios. Le decía su abuela. Creció y se desarrolló en el caos, en las raíces del conurbano, encontrando también la soledad colectiva de la muchedumbre. La falta de trabajo y oportunidades dio el paso a que la familia se mudara al sur.',
      'Le gustaba escribir, comenzó a hacerlo entrada la pubertad. Una forma de conectarse consigo misma, con sus emociones más profundas. Con la excusa de recabar información para algún futuro escrito o conocimiento de interés general, se había adaptado a las evasiones, muchas horas invertidas en pantallas, redes sociales, películas. Al fin y al cabo, era entretenimiento puro. Sentía una especie de culpa por esto. Cuando le aparecía esa sensación, la compensaba mediante el conocimiento que se adquiere de los libros. Su mayor miedo era perder la memoria por completo. Se sacó el pelo enrulado que el viento posó en su rostro y la misma rumiación de siempre tomó preponderancia. ¿Por qué escribo? Jugaba con la lapicera en sus dedos y tenía un pequeño cuaderno en su regazo. Anotó',
      'Escribo para explicar cómo se vivió en éste tiempo que nos toca atravesar como especie en la tierra. Quienes escribimos deberíamos ser custodios de la percepción y observación de lo que nos toca transitar. ¿Y para qué, con qué fin? Para ellos, los que vienen después.',
      'No estaba conforme. Lo tachó. En la profundidad, oculto, buscaba sentirse querida. Demostrar que no era sólo aquella que se manifiesta, sino también, la pretensión de que alguien la lea y pueda apreciar su proceso creativo. Cerró el cuaderno y miró al cielo. Anahí era una mujer a la que le costaba poder implicarse y ser responsable. No había encontrado, en sus veintidós años, un sentido de vida, capaz de encarnarlo y compartirlo con sus vínculos. Se encontraba en esa búsqueda personal. Su amiga Sonia Racón, se lo recordaba a menudo. Esa misma tarde, habían conversado sobre el asunto.',
      '¿Por qué no te involucrás? Con la carrera hiciste lo mismo. Estoy bien de esta manera, Sonia, ¿la estoy pasando mal? No se trata solo de vos, y de pasarla bien. Sin darte cuenta ejercés un daño a los demás. Vas a donde te lleva el viento. No sos clara. ¿Quién confía en alguien tan barrilete? Las personas no saben lo que quieren, que se hagan responsables la voz de Anahí tomó un tono defensivo. ¿Y tú responsabilidad? ¿tú propio deseo? Su amiga tenía razón. Cayó en la cuenta de que tenía un conflicto con su propio deseo. Se disolvía, se esfumaba, lo olvidaba. Pero no renunciaba a poder encontrarlo, captarlo y sostenerlo, aunque dudaba seriamente si eso era posible. Dejó de lado el pensamiento y se levantó con dificultad por la pereza. Fue hacia la puerta de madera que daba hacia el interior de su casa, un living pequeño con un sillón antiguo color manteca y una luz cálida que proyectaba un velador de pie. ¿Por qué no te involucras?... ¿y tú responsabilidad?... ¿tú propio deseo? repetía como un mantra en su cabeza. El crepúsculo iba dejando atrás sus colores más vívidos, para empezar a dar paso, a una noche bastante particular.',
      'Su madre Pola Cuyé, mediana estatura, pelo lacio negro y tez morena, bailaba en la cocina con lo que parecía ser una fuente de aluminio en sus manos. Anahí negó moviendo su cabeza y se mordió el labio inferior. Aunque esa actitud de su madre le generó una linda sensación en el pecho. Voy hasta la plaza, mamá, después vengo. No vuelvas tarde, hija, en una hora vamos a cenar. No llegó a escuchar lo que su madre dijo. Pegó un portazo y comenzó a caminar hacia la plaza del pueblo de Cumén. A ritmo rápido por las veredas desoladas, sintió frío y se puso la capucha de la campera para cubrirse. Algo llamó su atención, haciendo que disminuya la velocidad al llegar a la esquina y se oculte detrás de un cantero con grandes malvones en flor. Agudizó el oído intentando descifrar la conversación que tenían tres personas en el final de la vereda. Le había llamado la atención no reconocerlos. Cumén era un pueblo pequeño, la mayoría se reconocía al verse transitando por las calles. La que hablaba era una mujer. Cuando se active, tenemos sólo diez minutos para hacer el traslado, nos vienen siguiendo los pasos, estén atentos debemos ser cuidadosos. ¿Consiguieron lo que faltaba?',
      'Anahí estiró la cabeza para ver qué le estaban entregando, una curiosidad repentina energizó su cuerpo. Los dos sujetos restantes asintieron en silencio a la pregunta de la mujer. Anahí tomó otra posición porque no llegaba a divisar. Se agachó tocando el granito helado de la baldosa con su mano, siempre detrás del cantero. Tuvimos problemas con la llegada de la Salvia de Rets, pero se logró solucionar. Todo listo para mañana –la voz era de un hombre. Entregaba una caja de madera con forma de farol antiguo. Perfecto, mañana nos… –la mujer que había tomado la palabra se detuvo –. Tenemos visitas, dispérsense, mañana como quedamos –alertó mientras miraba la calle aledaña.',
      'Anahí también observó, pero no veía más que la oscuridad creciente de una noche cerrada. Cuando volvió su vista, ya no estaban. Una sensación de riesgo se le hizo presente. Sintió miedo en las extremidades de su cuerpo. Se le dificultó volver a ponerse en pie, pero al ver que nadie aparecía, aunque sentía en su cuerpo el acecho de un posible peligro inminente, se incorporó. Y desistió de ir hacia la plaza. Retornó directamente a su hogar, por precaución. –Ya cenamos, Ani –gritó su padre desde la cocina al escuchar la puerta. El olor a tuco, hizo que las tripas de Anahí vibraran y fue derecho hacia la olla. –¿Quién puede detenerse ante la delicia de mojar el pancito en la salsa? –preguntó con su brazo estirado y un pedazo de pan en sus manos. Rafael Rainez tenía el pelo corto color negro oscuro, muy carismatico y simpático. El humor era su defensa ante el mundo.',
      'Mientras degustaba como se deshacía la combinación de la harina y el tomate en su boca, Anahí pensaba que en ese pequeño acto, algo del hogar y la familia se jugaban. Sensaciones de seguridad, protección, comodidad y placer hicieron desaparecer la ansiedad devenida en peligro, sentida unos pocos minutos antes, en el afuera, ese lugar a veces tan ácido. –Es la salsa de los canelones, solo un pancito, no más. Y andá sentándote en la mesa. ¿De tu hermana sabés algo? –Rafael pispiaba el horno para medir cuánta cocción le faltaba a la pasta. –Hoy no la vi. –No mientas, ahora me ves –dijo Irupé acercándose a su hermana. Tenía el pelo negro por los hombros, los ojos parecidos a Rafael, grandes y expresivos. –¿Ahora me ves? ¿qué ves? –con una sonrisa, le pasó la lengua en un cachete dejándole un poco de saliva.',
      '–¡Qué asco! –el gesto de Anahí lo mostró en acción – ¡Te dije que no me lo hagas más, Irupé, seguís siendo una pendeja! –aunque Anahí le reprochaba a su hermana por su comportamiento, en el fondo le gustaba esa manifestación de afecto que se generaba entre ellas mediante el chiste y la ofensa. Irupé le tiró unos besitos al aire y fue hacia la bolsa de pan. –Guarden un poco de salsa para los canelones –insistió Rafael. –Esos canelones ya deben estar –dijo Pola mientras tomaba asiento en la mesa. –Ya los saco, que se hizo tarde –con dos repasadores en sus manos, dispuesto a sacar la fuente del horno. –Rafael… Mecha se quedó sin trabajo, la echaron de la agencia, dicen que como es temporada baja en turismo no necesitan tanto personal y están despidiendo gente –informó Pola compungida.',
      'Anahí pensaba que Pola se tomaba la vida con mucho drama. No le gustaba eso de su madre, quería ser distinta. Intentaba no caer en ese pensamiento que solía llevarla a discutir con ella. No dijo nada. Prefirió pensar en la empatía, en que entendía el malestar de su amiga. –Está jodida la mano, me crucé a Raúl el dueño del supermercado, me comentó que viene escuchando a la gente furiosa por el desempleo que se está dando en estos últimos tiempos. También me dijo que están desabasteciendo de productos, porque prefieren vender todo afuera –expuso Rafael mientras cortaba el canelón de verdura y ricota. –Hace años que venimos así, desde que tengo uso de razón que esto viene de mal en peor. En todas las provincias está pasando que se sufre la falta de laburo, no entiendo qué tiene que pasar en este país para que reaccionemos –la indignación apareció en Anahí. El timbre de la casa sonó. Luego unos golpes en la puerta. –¿Viene alguien a cenar?',
      '–No esperamos a nadie. Debe ser alguno que está vendiendo. ¿Vas vos?Mientras Anahí se levantaba de su silla para ir a abrir la puerta, observó que en la mesada había un colibrí de madera. –Qué lindo colibrí. ¿De dónde salió? –Me lo regaló esta mañana una señora en el mercado. Un amor de persona –respondió Pola mientras ponía la mesa para cenar. Anahí abrió. Un hombre de expresión fuerte, mirada penetrante, pelos entre canas y con el mentón en alto se presentó. –Buenas noches, ¿esta es la casa de la familia Zem? –Sí, ¿a quién busca? –Busco a la señora Pola Cuyé Zem, mi nombre es José Murnet, un viejo amigo de Inara. Disculpe mi atrevimiento, pero usted señorita es muy parecida. –Según me cuenta mi mamá, está en lo cierto. Pase por favor, ya le aviso. Inara Zem era su abuela. Había fallecido cuando era una niña. En la familia corría el rumor del parecido físico entre ellas. Esto no le disgustaba, la relación que forjaron en su infancia hizo crecer una conexión que llegaba palpitante a la actualidad. Identificación que no pudo romper ni disolver la muerte con sus artilugios. Pola y sus hijas se habían acostumbrado a utilizar el apellido de Inara. Rafael se enojaba cuando sus hijas usaban solo el apellido Zem, sentía que lo dejaban afuera. Comenzó como un juego entre Irupé y Anahí, pero con el paso del tiempo se hizo costumbre. Además, todas preferían el apellido materno. –Mamá, te buscan. –¿Quién es?',
    ],
  },
  {
    numeroCapitulo: '2',
    NombreCapitulo: 'Otros, Nosotros',
    Texto: [
      'El mundo de la magia existe, aunque muchos trabajan para mantenerlo oculto. Y debemos reconocerle que lo logran con mucha efectividad. Cualquiera podría pensar que esta declaración es un disparate o que la magia solo pertenece al mundo de la fantasía. Anahí Zem también lo creía. A veces, la vida nos pone adelante, eso que debemos reconocer y no logramos percibir. Se encontraba en la Calle de las Sensaciones, específicamente en el bar Al+. Sentada en una mesa que daba a la ventana, miró afuera, pocos deambulaban. Con detenimiento observó la carta. Llamó al mozo y le pidió una regresión en el tiempo, para recorrer el comienzo de su aventura. Con la intención de clarificar sus aspiraciones. Tal vez rememorando lo vivido, apareciera alguna señal. Esperó.',
      'Bebió un trago para darse ánimos. En la noche tendría la ceremonia de bienvenida a la Fortaleza de Lúzerin. Intentaría obtener para esa ocasión,  al menos una leve idea de dónde poner su cuerpo, en qué equipo ocupar un rol, dar su tiempo de vida, su trabajo cotidiano. Tomó los lentes, se los puso. Su memoria le lanzaba imágenes. Sintió que su cuerpo se estiraba. Perdió el sentido espacial y la conciencia. Cuando la recobró, se vió a sí misma, semi recostada en un sillón mugroso, abandonado en el frente de su casa. Vivía en un pequeño pueblo llamado Cumén, del lado de la costa atlántica, en la provincia de Santa Cruz, Argentina. Dos años caminando por las calles de tierra, el frío áspero del sur, la arena y el mar. El olor al mar la tranquilizaba. Cuando palpaba la soledad, extrañaba Buenos Aires, el oeste, el agite. La noche, las exposiciones de arte, la música en vivo, los bares. Nació una tarde de tormenta. Anahí, no sabes cómo llovía cuando naciste. Vos sí que vas a limpiar a varios. Le decía su abuela. Creció y se desarrolló en el caos, en las raíces del conurbano, encontrando también la soledad colectiva de la muchedumbre. La falta de trabajo y oportunidades dio el paso a que la familia se mudara al sur.',
      'Le gustaba escribir, comenzó a hacerlo entrada la pubertad. Una forma de conectarse consigo misma, con sus emociones más profundas. Con la excusa de recabar información para algún futuro escrito o conocimiento de interés general, se había adaptado a las evasiones, muchas horas invertidas en pantallas, redes sociales, películas. Al fin y al cabo, era entretenimiento puro. Sentía una especie de culpa por esto. Cuando le aparecía esa sensación, la compensaba mediante el conocimiento que se adquiere de los libros. Su mayor miedo era perder la memoria por completo. Se sacó el pelo enrulado que el viento posó en su rostro y la misma rumiación de siempre tomó preponderancia. ¿Por qué escribo? Jugaba con la lapicera en sus dedos y tenía un pequeño cuaderno en su regazo. Anotó',
      'Escribo para explicar cómo se vivió en éste tiempo que nos toca atravesar como especie en la tierra. Quienes escribimos deberíamos ser custodios de la percepción y observación de lo que nos toca transitar. ¿Y para qué, con qué fin? Para ellos, los que vienen después.',
      'No estaba conforme. Lo tachó. En la profundidad, oculto, buscaba sentirse querida. Demostrar que no era sólo aquella que se manifiesta, sino también, la pretensión de que alguien la lea y pueda apreciar su proceso creativo. Cerró el cuaderno y miró al cielo. Anahí era una mujer a la que le costaba poder implicarse y ser responsable. No había encontrado, en sus veintidós años, un sentido de vida, capaz de encarnarlo y compartirlo con sus vínculos. Se encontraba en esa búsqueda personal. Su amiga Sonia Racón, se lo recordaba a menudo. Esa misma tarde, habían conversado sobre el asunto.',
      '¿Por qué no te involucrás? Con la carrera hiciste lo mismo. Estoy bien de esta manera, Sonia, ¿la estoy pasando mal? No se trata solo de vos, y de pasarla bien. Sin darte cuenta ejercés un daño a los demás. Vas a donde te lleva el viento. No sos clara. ¿Quién confía en alguien tan barrilete? Las personas no saben lo que quieren, que se hagan responsables la voz de Anahí tomó un tono defensivo. ¿Y tú responsabilidad? ¿tú propio deseo? Su amiga tenía razón. Cayó en la cuenta de que tenía un conflicto con su propio deseo. Se disolvía, se esfumaba, lo olvidaba. Pero no renunciaba a poder encontrarlo, captarlo y sostenerlo, aunque dudaba seriamente si eso era posible. Dejó de lado el pensamiento y se levantó con dificultad por la pereza. Fue hacia la puerta de madera que daba hacia el interior de su casa, un living pequeño con un sillón antiguo color manteca y una luz cálida que proyectaba un velador de pie. ¿Por qué no te involucras?... ¿y tú responsabilidad?... ¿tú propio deseo? repetía como un mantra en su cabeza. El crepúsculo iba dejando atrás sus colores más vívidos, para empezar a dar paso, a una noche bastante particular.',
      'Su madre Pola Cuyé, mediana estatura, pelo lacio negro y tez morena, bailaba en la cocina con lo que parecía ser una fuente de aluminio en sus manos. Anahí negó moviendo su cabeza y se mordió el labio inferior. Aunque esa actitud de su madre le generó una linda sensación en el pecho. Voy hasta la plaza, mamá, después vengo. No vuelvas tarde, hija, en una hora vamos a cenar. No llegó a escuchar lo que su madre dijo. Pegó un portazo y comenzó a caminar hacia la plaza del pueblo de Cumén. A ritmo rápido por las veredas desoladas, sintió frío y se puso la capucha de la campera para cubrirse. Algo llamó su atención, haciendo que disminuya la velocidad al llegar a la esquina y se oculte detrás de un cantero con grandes malvones en flor. Agudizó el oído intentando descifrar la conversación que tenían tres personas en el final de la vereda. Le había llamado la atención no reconocerlos. Cumén era un pueblo pequeño, la mayoría se reconocía al verse transitando por las calles. La que hablaba era una mujer. Cuando se active, tenemos sólo diez minutos para hacer el traslado, nos vienen siguiendo los pasos, estén atentos debemos ser cuidadosos. ¿Consiguieron lo que faltaba?',
      'Anahí estiró la cabeza para ver qué le estaban entregando, una curiosidad repentina energizó su cuerpo. Los dos sujetos restantes asintieron en silencio a la pregunta de la mujer. Anahí tomó otra posición porque no llegaba a divisar. Se agachó tocando el granito helado de la baldosa con su mano, siempre detrás del cantero. Tuvimos problemas con la llegada de la Salvia de Rets, pero se logró solucionar. Todo listo para mañana –la voz era de un hombre. Entregaba una caja de madera con forma de farol antiguo. Perfecto, mañana nos… –la mujer que había tomado la palabra se detuvo –. Tenemos visitas, dispérsense, mañana como quedamos –alertó mientras miraba la calle aledaña.',
      'Anahí también observó, pero no veía más que la oscuridad creciente de una noche cerrada. Cuando volvió su vista, ya no estaban. Una sensación de riesgo se le hizo presente. Sintió miedo en las extremidades de su cuerpo. Se le dificultó volver a ponerse en pie, pero al ver que nadie aparecía, aunque sentía en su cuerpo el acecho de un posible peligro inminente, se incorporó. Y desistió de ir hacia la plaza. Retornó directamente a su hogar, por precaución. –Ya cenamos, Ani –gritó su padre desde la cocina al escuchar la puerta. El olor a tuco, hizo que las tripas de Anahí vibraran y fue derecho hacia la olla. –¿Quién puede detenerse ante la delicia de mojar el pancito en la salsa? –preguntó con su brazo estirado y un pedazo de pan en sus manos. Rafael Rainez tenía el pelo corto color negro oscuro, muy carismatico y simpático. El humor era su defensa ante el mundo.',
      'Mientras degustaba como se deshacía la combinación de la harina y el tomate en su boca, Anahí pensaba que en ese pequeño acto, algo del hogar y la familia se jugaban. Sensaciones de seguridad, protección, comodidad y placer hicieron desaparecer la ansiedad devenida en peligro, sentida unos pocos minutos antes, en el afuera, ese lugar a veces tan ácido. –Es la salsa de los canelones, solo un pancito, no más. Y andá sentándote en la mesa. ¿De tu hermana sabés algo? –Rafael pispiaba el horno para medir cuánta cocción le faltaba a la pasta. –Hoy no la vi. –No mientas, ahora me ves –dijo Irupé acercándose a su hermana. Tenía el pelo negro por los hombros, los ojos parecidos a Rafael, grandes y expresivos. –¿Ahora me ves? ¿qué ves? –con una sonrisa, le pasó la lengua en un cachete dejándole un poco de saliva.',
      '–¡Qué asco! –el gesto de Anahí lo mostró en acción – ¡Te dije que no me lo hagas más, Irupé, seguís siendo una pendeja! –aunque Anahí le reprochaba a su hermana por su comportamiento, en el fondo le gustaba esa manifestación de afecto que se generaba entre ellas mediante el chiste y la ofensa. Irupé le tiró unos besitos al aire y fue hacia la bolsa de pan. –Guarden un poco de salsa para los canelones –insistió Rafael. –Esos canelones ya deben estar –dijo Pola mientras tomaba asiento en la mesa. –Ya los saco, que se hizo tarde –con dos repasadores en sus manos, dispuesto a sacar la fuente del horno. –Rafael… Mecha se quedó sin trabajo, la echaron de la agencia, dicen que como es temporada baja en turismo no necesitan tanto personal y están despidiendo gente –informó Pola compungida.',
      'Anahí pensaba que Pola se tomaba la vida con mucho drama. No le gustaba eso de su madre, quería ser distinta. Intentaba no caer en ese pensamiento que solía llevarla a discutir con ella. No dijo nada. Prefirió pensar en la empatía, en que entendía el malestar de su amiga. –Está jodida la mano, me crucé a Raúl el dueño del supermercado, me comentó que viene escuchando a la gente furiosa por el desempleo que se está dando en estos últimos tiempos. También me dijo que están desabasteciendo de productos, porque prefieren vender todo afuera –expuso Rafael mientras cortaba el canelón de verdura y ricota. –Hace años que venimos así, desde que tengo uso de razón que esto viene de mal en peor. En todas las provincias está pasando que se sufre la falta de laburo, no entiendo qué tiene que pasar en este país para que reaccionemos –la indignación apareció en Anahí. El timbre de la casa sonó. Luego unos golpes en la puerta. –¿Viene alguien a cenar?',
      '–No esperamos a nadie. Debe ser alguno que está vendiendo. ¿Vas vos?Mientras Anahí se levantaba de su silla para ir a abrir la puerta, observó que en la mesada había un colibrí de madera. –Qué lindo colibrí. ¿De dónde salió? –Me lo regaló esta mañana una señora en el mercado. Un amor de persona –respondió Pola mientras ponía la mesa para cenar. Anahí abrió. Un hombre de expresión fuerte, mirada penetrante, pelos entre canas y con el mentón en alto se presentó. –Buenas noches, ¿esta es la casa de la familia Zem? –Sí, ¿a quién busca? –Busco a la señora Pola Cuyé Zem, mi nombre es José Murnet, un viejo amigo de Inara. Disculpe mi atrevimiento, pero usted señorita es muy parecida. –Según me cuenta mi mamá, está en lo cierto. Pase por favor, ya le aviso. Inara Zem era su abuela. Había fallecido cuando era una niña. En la familia corría el rumor del parecido físico entre ellas. Esto no le disgustaba, la relación que forjaron en su infancia hizo crecer una conexión que llegaba palpitante a la actualidad. Identificación que no pudo romper ni disolver la muerte con sus artilugios. Pola y sus hijas se habían acostumbrado a utilizar el apellido de Inara. Rafael se enojaba cuando sus hijas usaban solo el apellido Zem, sentía que lo dejaban afuera. Comenzó como un juego entre Irupé y Anahí, pero con el paso del tiempo se hizo costumbre. Además, todas preferían el apellido materno. –Mamá, te buscan. –¿Quién es?',
    ],
  },
]
const texto = [
  'El mundo de la magia existe, aunque muchos trabajan para mantenerlo oculto. Y debemos reconocerle que lo logran con mucha efectividad. Cualquiera podría pensar que esta declaración es un disparate o que la magia solo pertenece al mundo de la fantasía. Anahí Zem también lo creía. A veces, la vida nos pone adelante, eso que debemos reconocer y no logramos percibir. Se encontraba en la Calle de las Sensaciones, específicamente en el bar Al+. Sentada en una mesa que daba a la ventana, miró afuera, pocos deambulaban. Con detenimiento observó la carta. Llamó al mozo y le pidió una regresión en el tiempo, para recorrer el comienzo de su aventura. Con la intención de clarificar sus aspiraciones. Tal vez rememorando lo vivido, apareciera alguna señal. Esperó.',
  'Bebió un trago para darse ánimos. En la noche tendría la ceremonia de bienvenida a la Fortaleza de Lúzerin. Intentaría obtener para esa ocasión,  al menos una leve idea de dónde poner su cuerpo, en qué equipo ocupar un rol, dar su tiempo de vida, su trabajo cotidiano. Tomó los lentes, se los puso. Su memoria le lanzaba imágenes. Sintió que su cuerpo se estiraba. Perdió el sentido espacial y la conciencia. Cuando la recobró, se vió a sí misma, semi recostada en un sillón mugroso, abandonado en el frente de su casa. Vivía en un pequeño pueblo llamado Cumén, del lado de la costa atlántica, en la provincia de Santa Cruz, Argentina. Dos años caminando por las calles de tierra, el frío áspero del sur, la arena y el mar. El olor al mar la tranquilizaba. Cuando palpaba la soledad, extrañaba Buenos Aires, el oeste, el agite. La noche, las exposiciones de arte, la música en vivo, los bares. Nació una tarde de tormenta. Anahí, no sabes cómo llovía cuando naciste. Vos sí que vas a limpiar a varios. Le decía su abuela. Creció y se desarrolló en el caos, en las raíces del conurbano, encontrando también la soledad colectiva de la muchedumbre. La falta de trabajo y oportunidades dio el paso a que la familia se mudara al sur.',
  'Le gustaba escribir, comenzó a hacerlo entrada la pubertad. Una forma de conectarse consigo misma, con sus emociones más profundas. Con la excusa de recabar información para algún futuro escrito o conocimiento de interés general, se había adaptado a las evasiones, muchas horas invertidas en pantallas, redes sociales, películas. Al fin y al cabo, era entretenimiento puro. Sentía una especie de culpa por esto. Cuando le aparecía esa sensación, la compensaba mediante el conocimiento que se adquiere de los libros. Su mayor miedo era perder la memoria por completo. Se sacó el pelo enrulado que el viento posó en su rostro y la misma rumiación de siempre tomó preponderancia. ¿Por qué escribo? Jugaba con la lapicera en sus dedos y tenía un pequeño cuaderno en su regazo. Anotó',
  'Escribo para explicar cómo se vivió en éste tiempo que nos toca atravesar como especie en la tierra. Quienes escribimos deberíamos ser custodios de la percepción y observación de lo que nos toca transitar. ¿Y para qué, con qué fin? Para ellos, los que vienen después.',
  'No estaba conforme. Lo tachó. En la profundidad, oculto, buscaba sentirse querida. Demostrar que no era sólo aquella que se manifiesta, sino también, la pretensión de que alguien la lea y pueda apreciar su proceso creativo. Cerró el cuaderno y miró al cielo. Anahí era una mujer a la que le costaba poder implicarse y ser responsable. No había encontrado, en sus veintidós años, un sentido de vida, capaz de encarnarlo y compartirlo con sus vínculos. Se encontraba en esa búsqueda personal. Su amiga Sonia Racón, se lo recordaba a menudo. Esa misma tarde, habían conversado sobre el asunto.',
  '¿Por qué no te involucrás? Con la carrera hiciste lo mismo. Estoy bien de esta manera, Sonia, ¿la estoy pasando mal? No se trata solo de vos, y de pasarla bien. Sin darte cuenta ejercés un daño a los demás. Vas a donde te lleva el viento. No sos clara. ¿Quién confía en alguien tan barrilete? Las personas no saben lo que quieren, que se hagan responsables la voz de Anahí tomó un tono defensivo. ¿Y tú responsabilidad? ¿tú propio deseo? Su amiga tenía razón. Cayó en la cuenta de que tenía un conflicto con su propio deseo. Se disolvía, se esfumaba, lo olvidaba. Pero no renunciaba a poder encontrarlo, captarlo y sostenerlo, aunque dudaba seriamente si eso era posible. Dejó de lado el pensamiento y se levantó con dificultad por la pereza. Fue hacia la puerta de madera que daba hacia el interior de su casa, un living pequeño con un sillón antiguo color manteca y una luz cálida que proyectaba un velador de pie. ¿Por qué no te involucras?... ¿y tú responsabilidad?... ¿tú propio deseo? repetía como un mantra en su cabeza. El crepúsculo iba dejando atrás sus colores más vívidos, para empezar a dar paso, a una noche bastante particular.',
  'Su madre Pola Cuyé, mediana estatura, pelo lacio negro y tez morena, bailaba en la cocina con lo que parecía ser una fuente de aluminio en sus manos. Anahí negó moviendo su cabeza y se mordió el labio inferior. Aunque esa actitud de su madre le generó una linda sensación en el pecho. Voy hasta la plaza, mamá, después vengo. No vuelvas tarde, hija, en una hora vamos a cenar. No llegó a escuchar lo que su madre dijo. Pegó un portazo y comenzó a caminar hacia la plaza del pueblo de Cumén. A ritmo rápido por las veredas desoladas, sintió frío y se puso la capucha de la campera para cubrirse. Algo llamó su atención, haciendo que disminuya la velocidad al llegar a la esquina y se oculte detrás de un cantero con grandes malvones en flor. Agudizó el oído intentando descifrar la conversación que tenían tres personas en el final de la vereda. Le había llamado la atención no reconocerlos. Cumén era un pueblo pequeño, la mayoría se reconocía al verse transitando por las calles. La que hablaba era una mujer. Cuando se active, tenemos sólo diez minutos para hacer el traslado, nos vienen siguiendo los pasos, estén atentos debemos ser cuidadosos. ¿Consiguieron lo que faltaba?',
  'Anahí estiró la cabeza para ver qué le estaban entregando, una curiosidad repentina energizó su cuerpo. Los dos sujetos restantes asintieron en silencio a la pregunta de la mujer. Anahí tomó otra posición porque no llegaba a divisar. Se agachó tocando el granito helado de la baldosa con su mano, siempre detrás del cantero. Tuvimos problemas con la llegada de la Salvia de Rets, pero se logró solucionar. Todo listo para mañana –la voz era de un hombre. Entregaba una caja de madera con forma de farol antiguo. Perfecto, mañana nos… –la mujer que había tomado la palabra se detuvo –. Tenemos visitas, dispérsense, mañana como quedamos –alertó mientras miraba la calle aledaña.',
  'Anahí también observó, pero no veía más que la oscuridad creciente de una noche cerrada. Cuando volvió su vista, ya no estaban. Una sensación de riesgo se le hizo presente. Sintió miedo en las extremidades de su cuerpo. Se le dificultó volver a ponerse en pie, pero al ver que nadie aparecía, aunque sentía en su cuerpo el acecho de un posible peligro inminente, se incorporó. Y desistió de ir hacia la plaza. Retornó directamente a su hogar, por precaución. –Ya cenamos, Ani –gritó su padre desde la cocina al escuchar la puerta. El olor a tuco, hizo que las tripas de Anahí vibraran y fue derecho hacia la olla. –¿Quién puede detenerse ante la delicia de mojar el pancito en la salsa? –preguntó con su brazo estirado y un pedazo de pan en sus manos. Rafael Rainez tenía el pelo corto color negro oscuro, muy carismatico y simpático. El humor era su defensa ante el mundo.',
  'Mientras degustaba como se deshacía la combinación de la harina y el tomate en su boca, Anahí pensaba que en ese pequeño acto, algo del hogar y la familia se jugaban. Sensaciones de seguridad, protección, comodidad y placer hicieron desaparecer la ansiedad devenida en peligro, sentida unos pocos minutos antes, en el afuera, ese lugar a veces tan ácido. –Es la salsa de los canelones, solo un pancito, no más. Y andá sentándote en la mesa. ¿De tu hermana sabés algo? –Rafael pispiaba el horno para medir cuánta cocción le faltaba a la pasta. –Hoy no la vi. –No mientas, ahora me ves –dijo Irupé acercándose a su hermana. Tenía el pelo negro por los hombros, los ojos parecidos a Rafael, grandes y expresivos. –¿Ahora me ves? ¿qué ves? –con una sonrisa, le pasó la lengua en un cachete dejándole un poco de saliva.',
  '–¡Qué asco! –el gesto de Anahí lo mostró en acción – ¡Te dije que no me lo hagas más, Irupé, seguís siendo una pendeja! –aunque Anahí le reprochaba a su hermana por su comportamiento, en el fondo le gustaba esa manifestación de afecto que se generaba entre ellas mediante el chiste y la ofensa. Irupé le tiró unos besitos al aire y fue hacia la bolsa de pan. –Guarden un poco de salsa para los canelones –insistió Rafael. –Esos canelones ya deben estar –dijo Pola mientras tomaba asiento en la mesa. –Ya los saco, que se hizo tarde –con dos repasadores en sus manos, dispuesto a sacar la fuente del horno. –Rafael… Mecha se quedó sin trabajo, la echaron de la agencia, dicen que como es temporada baja en turismo no necesitan tanto personal y están despidiendo gente –informó Pola compungida.',
  'Anahí pensaba que Pola se tomaba la vida con mucho drama. No le gustaba eso de su madre, quería ser distinta. Intentaba no caer en ese pensamiento que solía llevarla a discutir con ella. No dijo nada. Prefirió pensar en la empatía, en que entendía el malestar de su amiga. –Está jodida la mano, me crucé a Raúl el dueño del supermercado, me comentó que viene escuchando a la gente furiosa por el desempleo que se está dando en estos últimos tiempos. También me dijo que están desabasteciendo de productos, porque prefieren vender todo afuera –expuso Rafael mientras cortaba el canelón de verdura y ricota. –Hace años que venimos así, desde que tengo uso de razón que esto viene de mal en peor. En todas las provincias está pasando que se sufre la falta de laburo, no entiendo qué tiene que pasar en este país para que reaccionemos –la indignación apareció en Anahí. El timbre de la casa sonó. Luego unos golpes en la puerta. –¿Viene alguien a cenar?',
  '–No esperamos a nadie. Debe ser alguno que está vendiendo. ¿Vas vos?Mientras Anahí se levantaba de su silla para ir a abrir la puerta, observó que en la mesada había un colibrí de madera. –Qué lindo colibrí. ¿De dónde salió? –Me lo regaló esta mañana una señora en el mercado. Un amor de persona –respondió Pola mientras ponía la mesa para cenar. Anahí abrió. Un hombre de expresión fuerte, mirada penetrante, pelos entre canas y con el mentón en alto se presentó. –Buenas noches, ¿esta es la casa de la familia Zem? –Sí, ¿a quién busca? –Busco a la señora Pola Cuyé Zem, mi nombre es José Murnet, un viejo amigo de Inara. Disculpe mi atrevimiento, pero usted señorita es muy parecida. –Según me cuenta mi mamá, está en lo cierto. Pase por favor, ya le aviso. Inara Zem era su abuela. Había fallecido cuando era una niña. En la familia corría el rumor del parecido físico entre ellas. Esto no le disgustaba, la relación que forjaron en su infancia hizo crecer una conexión que llegaba palpitante a la actualidad. Identificación que no pudo romper ni disolver la muerte con sus artilugios. Pola y sus hijas se habían acostumbrado a utilizar el apellido de Inara. Rafael se enojaba cuando sus hijas usaban solo el apellido Zem, sentía que lo dejaban afuera. Comenzó como un juego entre Irupé y Anahí, pero con el paso del tiempo se hizo costumbre. Además, todas preferían el apellido materno. –Mamá, te buscan. –¿Quién es?',
]

const scrollDown = document.querySelector('.scroll-down')
const scrollIcon = document.querySelector('.scroll-icon')
const scrollText = document.querySelector('.scroll-text')
const returnMap = document.querySelector('.return-map')

const sectionOne = document.querySelector('section#welcome')
let text = document.querySelector('.text')
let innerText = document.querySelector('.inner-text')
let slides = document.querySelectorAll('.slide')
const backTop = document.querySelector('.back-to-top')

let actualChapter = 1
let pageHeight = 0
let finishedChapters = actualChapter - 1

const killCopy = function (e) {
  return false
}
const reEnable = function () {
  return true
}

toggle.addEventListener('click', () => {
  nav.classList.toggle('active')
})

const readingMotor = function () {
  const chapter = document.querySelector('section.chapter')

  document.onselectstart = new Function('return false')
  if (window.sidebar) {
    document.onmousedown = killCopy
    document.onclick = reEnable
  }

  let count = 0
  while (count < texto.length) {
    const paragraph = document.createElement('p')
    paragraph.classList.add('slide')
    paragraph.innerText = `${texto[count]}`
    chapter.append(paragraph)
    count++
  }
  backTop.addEventListener('click', () => {
    scrollIcon.remove()
    scrollText.remove()
    returnMap.style.display = 'block'
    returnMap.disabled = false

    returnMap.addEventListener('click', readingCount)
  })
}

const readingCount = function () {
  actualChapter++
  console.log(actualChapter)
}

//const reading = function () {

window.addEventListener('scroll', () => {
  let slides = document.querySelectorAll('.slide')
  let value = window.scrollY
  sectionOne.style.clipPath = `circle(${value}px at center center)`
  text.style.left = `${100 - value / 5}%`
  innerText.style.left = `${100 - value / 5}%`

  const triggerBottom = (window.innerHeight / 5) * 4
  slides.forEach((slide) => {
    const slideTop = slide.getBoundingClientRect().top
    if (slideTop < triggerBottom) {
      slide.classList.add('in')
    } else {
      slide.classList.remove('in')
    }
  })
})

window.onload = readingMotor
